"""
Safe file discovery and language classification for the DevPilot scanner.

Responsibilities:
  - Walk a repository root exactly once.
  - Classify each file by language.
  - Detect and skip binary files.
  - Detect and flag generated/minified files.
  - Enforce configurable resource limits (max files, max size, max depth).
  - Resolve symlinks safely (no escape from root).
  - Return a DiscoveredFile list for all analyzers to share.

One invocation of discover_files() is sufficient for an entire scan.
Analyzers must not re-walk the filesystem.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Set


# ---------------------------------------------------------------------------
# Limits (tunable via ScanConfig)
# ---------------------------------------------------------------------------

MAX_FILE_SIZE_BYTES: int = 512 * 1024   # 512 KB
MAX_FILES: int = 5_000
MAX_DEPTH: int = 20

# ---------------------------------------------------------------------------
# Directories always skipped
# ---------------------------------------------------------------------------

IGNORED_DIRS: Set[str] = {
    ".git",
    ".svn",
    ".hg",
    ".venv",
    "venv",
    ".env",           # NOT the .env file — this is a dir name
    "node_modules",
    "__pycache__",
    ".next",
    ".nuxt",
    "dist",
    "build",
    "out",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    "htmlcov",
    "coverage",
    ".coverage",
    ".cache",
    ".parcel-cache",
    "target",         # Rust/Java
    ".gradle",
    ".idea",
    ".vscode",
}

# ---------------------------------------------------------------------------
# Language → extensions mapping
# ---------------------------------------------------------------------------

LANGUAGE_BY_EXTENSION: Dict[str, str] = {
    ".py":   "python",
    ".js":   "javascript",
    ".jsx":  "javascript",
    ".ts":   "typescript",
    ".tsx":  "typescript",
    ".java": "java",
    ".go":   "go",
    ".rs":   "rust",
    ".php":  "php",
    ".rb":   "ruby",
    ".cpp":  "cpp",
    ".cxx":  "cpp",
    ".cc":   "cpp",
    ".c":    "c",
    ".h":    "c",
    ".hpp":  "cpp",
    ".sh":   "shell",
    ".bash": "shell",
    ".zsh":  "shell",
    ".json": "json",
    ".yaml": "yaml",
    ".yml":  "yaml",
    ".html": "html",
    ".htm":  "html",
    ".xml":  "xml",
    ".toml": "toml",
    ".tf":   "terraform",
    ".env":  "env",
}

# Languages where AST/structural analysis is meaningful
ANALYZABLE_LANGUAGES: Set[str] = {
    "python", "javascript", "typescript",
    "java", "go", "rust", "php", "ruby",
    "shell", "json", "yaml", "html", "env",
}

# ---------------------------------------------------------------------------
# Binary detection helpers
# ---------------------------------------------------------------------------

# Extensions that are always binary — skip content analysis entirely
_BINARY_EXTENSIONS: Set[str] = {
    ".pyc", ".pyo", ".pyd",
    ".so", ".dylib", ".dll", ".lib", ".a", ".o",
    ".exe", ".bin", ".out",
    ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar",
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".svg",
    ".mp3", ".mp4", ".avi", ".mov", ".wav",
    ".pdf", ".docx", ".xlsx", ".pptx",
    ".db", ".sqlite", ".sqlite3",
    ".woff", ".woff2", ".ttf", ".eot",
    ".class",      # Java bytecode
    ".wasm",
}

# Null-byte threshold for binary detection in text-ish files
_NULL_BYTE_SAMPLE_SIZE = 8192
_MAX_NULL_BYTES_RATIO = 0.01  # >1% null bytes → treat as binary


# ---------------------------------------------------------------------------
# Generated/minified file detection
# ---------------------------------------------------------------------------

_MINIFIED_LINE_LEN_THRESHOLD = 500  # lines longer than this in JS/TS → minified
_GENERATED_HEADERS = [
    "// generated",
    "// auto-generated",
    "// do not edit",
    "# generated by",
    "# auto-generated",
    "# do not edit",
    "/* generated",
    "/* auto-generated",
    "THIS FILE IS AUTO-GENERATED",
    "Code generated by",
    "DO NOT EDIT",
]

_GENERATED_NAME_RE = re.compile(
    r"(?:\.min\.|\.bundle\.|\.generated\.|\.pb\.go$|_pb2\.py$|\.g\.dart)",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


@dataclass
class ScanConfig:
    """Configurable limits for a scan run."""
    max_file_size: int = MAX_FILE_SIZE_BYTES
    max_files: int = MAX_FILES
    max_depth: int = MAX_DEPTH
    skip_generated: bool = True
    skip_minified: bool = True


@dataclass
class DiscoveredFile:
    """Metadata about a single file in the scanned repository."""

    absolute_path: Path
    relative_path: str           # relative to repository root
    language: Optional[str]      # "python" | "javascript" | None
    extension: str               # ".py" | ".js" etc.
    size_bytes: int
    is_binary: bool = False
    is_generated: bool = False
    is_minified: bool = False
    content: Optional[str] = None  # populated only for non-binary scannable files

    @property
    def is_scannable(self) -> bool:
        return (
            not self.is_binary
            and not self.is_generated
            and not self.is_minified
            and self.language in ANALYZABLE_LANGUAGES
            and self.content is not None
        )


@dataclass
class DiscoveryResult:
    """Output of discover_files()."""

    files: List[DiscoveredFile] = field(default_factory=list)
    skipped_binary: int = 0
    skipped_generated: int = 0
    skipped_large: int = 0
    skipped_depth: int = 0
    total_walked: int = 0
    languages_found: Set[str] = field(default_factory=set)
    truncated: bool = False       # True if MAX_FILES was reached


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def discover_files(root: Path, config: Optional[ScanConfig] = None) -> DiscoveryResult:
    """
    Walk *root* and classify all files.

    Returns a DiscoveryResult whose .files list can be shared across all
    analyzers. The filesystem is walked exactly once.

    Safety guarantees:
    - Symlinks are resolved and validated to stay within root.
    - Binary files are detected by extension and byte sampling.
    - Files larger than config.max_file_size are skipped.
    - Generated/minified files are flagged and skipped from analysis.
    - Depth is limited to config.max_depth.
    - Total files are capped at config.max_files.
    """
    if config is None:
        config = ScanConfig()

    result = DiscoveryResult()
    root_resolved = root.resolve()

    _walk(root_resolved, root_resolved, config, result, depth=0)

    return result


# ---------------------------------------------------------------------------
# Internal walk
# ---------------------------------------------------------------------------


def _walk(
    root: Path,
    current: Path,
    config: ScanConfig,
    result: DiscoveryResult,
    depth: int,
) -> None:
    if depth > config.max_depth:
        result.skipped_depth += 1
        return

    try:
        entries = list(current.iterdir())
    except PermissionError:
        return
    except OSError:
        return

    for entry in entries:
        # Resolve symlinks and verify containment
        try:
            resolved = entry.resolve()
        except OSError:
            continue

        # Symlink escape protection: must stay inside root
        try:
            resolved.relative_to(root)
        except ValueError:
            continue  # symlink escapes repository root — skip

        if resolved.is_dir():
            # Skip ignored directories
            if entry.name in IGNORED_DIRS:
                continue
            if result.truncated:
                return
            _walk(root, resolved, config, result, depth + 1)

        elif resolved.is_file():
            result.total_walked += 1

            if len(result.files) >= config.max_files:
                result.truncated = True
                return

            df = _classify_file(root, resolved, config)
            if df is not None:
                result.files.append(df)
                if df.language:
                    result.languages_found.add(df.language)


def _classify_file(
    root: Path,
    path: Path,
    config: ScanConfig,
) -> Optional[DiscoveredFile]:
    """Classify and optionally load a single file."""
    try:
        size = path.stat().st_size
    except OSError:
        return None

    extension = path.suffix.lower()
    language = LANGUAGE_BY_EXTENSION.get(extension)

    # Always-binary extensions
    if extension in _BINARY_EXTENSIONS:
        return DiscoveredFile(
            absolute_path=path,
            relative_path=str(path.relative_to(root)),
            language=language,
            extension=extension,
            size_bytes=size,
            is_binary=True,
        )

    # Size limit
    if size > config.max_file_size:
        return DiscoveredFile(
            absolute_path=path,
            relative_path=str(path.relative_to(root)),
            language=language,
            extension=extension,
            size_bytes=size,
            content=None,  # too large to load
        )

    # No known extension — still classify but mark no language
    # Load content for binary/generated detection
    try:
        raw = path.read_bytes()
    except OSError:
        return None

    # Binary byte detection
    if _is_binary_content(raw):
        return DiscoveredFile(
            absolute_path=path,
            relative_path=str(path.relative_to(root)),
            language=language,
            extension=extension,
            size_bytes=size,
            is_binary=True,
        )

    # Decode text
    try:
        content = raw.decode("utf-8", errors="replace")
    except Exception:
        return DiscoveredFile(
            absolute_path=path,
            relative_path=str(path.relative_to(root)),
            language=language,
            extension=extension,
            size_bytes=size,
            is_binary=True,
        )

    # Generated file detection
    is_generated = False
    is_minified = False

    if config.skip_generated and _is_generated(path, content):
        is_generated = True

    if config.skip_minified and language in ("javascript", "typescript") and _is_minified(content):
        is_minified = True

    return DiscoveredFile(
        absolute_path=path,
        relative_path=str(path.relative_to(root)),
        language=language,
        extension=extension,
        size_bytes=size,
        is_generated=is_generated,
        is_minified=is_minified,
        content=content if (language in ANALYZABLE_LANGUAGES) else None,
    )


def _is_binary_content(raw: bytes) -> bool:
    """Heuristic: check for null bytes in the first sample."""
    sample = raw[:_NULL_BYTE_SAMPLE_SIZE]
    if not sample:
        return False
    null_count = sample.count(b"\x00")
    return (null_count / len(sample)) > _MAX_NULL_BYTES_RATIO


def _is_generated(path: Path, content: str) -> bool:
    """Detect files that are auto-generated and should not be analyzed."""
    # Filename-based detection
    name = path.name
    if _GENERATED_NAME_RE.search(name):
        return True

    # Header-based detection (check first 10 lines)
    first_lines = content[:1000].upper()
    for marker in _GENERATED_HEADERS:
        if marker.upper() in first_lines:
            return True

    return False


def _is_minified(content: str) -> bool:
    """Detect minified JS/TS: very long single lines."""
    lines = content.splitlines()
    if not lines:
        return False
    long_lines = sum(1 for ln in lines if len(ln) > _MINIFIED_LINE_LEN_THRESHOLD)
    # If more than 20% of lines are very long, treat as minified
    return long_lines > 0 and (long_lines / len(lines)) > 0.2
